topics:
- name    : joy
  topic   : /door1/rc_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : /door1/twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : external
  topic   : /door1/cmd_vel
  timeout : 0.5
  priority: 1
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
